### ISSUE TITLE
Project views directory inference doesn't seem to work

### ISSUE THREAD

**Issue by lukaszwawrzyk** [JetBrains/bazel-bsp#120]
It is not documented enough. I didn't know where to put the `projectview.bazelproject`, I hoped it would be .bsp dir, but it seems to be at repository root. It is hard to figure out from code. Also I found some undocumented way of passing targets through command line (?). Not sure how to use it. 

I tried with following content:

```yaml
directories:
  server/src/main/java/org/jetbrains/bsp/bazel/server/bep

derive_targets_from_directories: true

targets:

additional_languages:
  kotlin
  python
  scala
```

Nothing was imported. I had to add targets as well:

```yaml
directories:
  server/src/main/java/org/jetbrains/bsp/bazel/server/bep

derive_targets_from_directories: true

targets:
  //server/src/main/java/org/jetbrains/bsp/bazel/server/bep/...:all

additional_languages:
  kotlin
  python
  scala
```
